### ISSUE TITLE
Open tasks for SDK

### ISSUE THREAD

**Issue by adrianbroher** [freeorion/freeorion-sdk#14]
This issue contains things to check before declaring the setup working:
- [x] Travis-CI doesn't contain any artifact deployment as Github Release.
- [x] Validate MacOSX SDK file layout.
- [x] Validate MacOSX SDK ABI compability.
- [x] Check if MacOSX build flags are matching the regular upstream build flags for all dependencies.
- [ ] Validate Windows SDK ABI compability.
- [ ] Check if Windows build flags are matching the regular upstream build flags for all dependencies.
- [x] Write initial ChangeLog.md.

**Comment by adrianbroher** [comment]
@Vezzra 

What is the status on the SDK? Does the latest iteration work properly for you?

Also what is the command line you use to package the dmg file?

**Comment by Vezzra** [comment]
Sorry for my lack of response, have been (and still am) occupied by my autumn break activities and the aftermath... 😉 

> What is the status on the SDK? Does the latest iteration work properly for you?

Layout of the generated `dep` folder looks fine now, but we're not there yet, I still get a few errors. Opened issue #15, see there.

> Also what is the command line you use to package the dmg file?

I always used the OSX Disk Utility GUI app to produce the dmg file, but of course that can be done via a shell command:
```
hdiutil create -volname FreeOrionSDK -megabytes 100 -srcfolder <folder_containing_sdk> -ov -format UDZO <dmg_file_path>
```
For the folder structure and file names used see the current SDK, these have to be exactly as they are there, otherwise the `bootstrap.command` shell script won't work properly.

The `folder_containing_sdk` path needs to specify the *parent* directory of the `FreeOrionSDK` folder you want to package, *not* the `FreeOrionSDK` folder itself, otherwise the resulting dmg file will contain the *contents* of the `FreeOrionSDK` folder.

While that isn't a big issue, I found that having this top level folder in the dmg file is more convenient to use. You can just drag the entire folder out of the mounted dmg volume to wherever you want (and optionally rename it afterwards). Otherwise you have to create a new empty folder first and then drag all the contents of the mounted dmg volume into that folder. A tad more inconvenient IMO 😉

**Comment by adrianbroher** [comment]
To be honest I don't get your comment about the layout (like in 'don't understand', not 'don't agree').

The new and old SDK have the same layout?  At lease from what I can see with my tools.

Same goes for [freeorion/freeorion#1097](https://github.com/freeorion/freeorion/pull/1097#issuecomment-259958474).

When looking at the [output of the travis build](https://travis-ci.org/freeorion/freeorion/jobs/174827694#L54-L56) it is already mounted at `/Volumes/FreeOrionSDK`   so what is the point of having another `FreeOrionSDK` folder?

**Comment by Vezzra** [comment]
The layout of the old and new SDK are the same now, that's correct, I'm merely talking about the folder structure within the DMG file. Contrary to a zip archive or a tarball, DMGs are no archives like those, but actually image files like ISOs. You cannot right-click on them and unpack their contents into an empty folder like you can do with typical archives, you can only mount them like ISO images and then copy/drag and drop their contents.

Which means the point of having another "FreeOrionSDK" (or whatever we might want to call it) folder which contains the actual SDK within the DMG is to enable the user to copy/drag and drop that entire folder as it is to the desired location (and subsequently rename the folder if desired).

You can't copy/drag and drop the mountpoint (`/Volumes/FreeOrionSDK`) in OSXs default GUI shell Finder, only its contents. Of course, when using the command line or apps like "muCommander" that's possible, but usually you do the basic file management stuff in Finder. And in Finder you'll first have to manually create the empty folder you want to copy the contents of the mounted DMG to.

As I said, only a minor issue/inconvenience, so only change the cmake scripts to provide that extra folder level if it's not too complicated. It's not really worth making things complex and error prune.

**Comment by adrianbroher** [comment]
There was no feedback indicating Windows SDK ABI incompatibility, therefor closing this issue.
