### ISSUE TITLE
Can't Link GLEW when building FreeOrion (GiGiSDL) with Windows x64 SDK

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion-sdk#67]
When trying to build FreeOrion in x64 configuration against the x64 SDK, I get a bunch of GLEW link errors. After I downloaded the [GLEW binaries](http://glew.sourceforge.net/) and replaced the .lib in the SDK with the x64 .lib from the download, the linker errors went away.

**Comment by geoffthemedio** [comment]
After also replacing `glew32.dll` I can build and run FreeOrion in x64 configuration.

**Comment by hifron** [comment]
There is option(on Windows x64) to use [Conda-Forge.org](https://www.conda-forge.org) with [anaconda.org/conda-forge](https://anaconda.org/) default repository in package [miniforge](https://github.com/conda-forge/miniforge/#download) and added conda-forge repository with:
`
conda config --add channels conda-forge

conda config --set channel_priority strict

conda install package-name
`

and then install freeorion dependencies(package names could be checked on anaconda.org) on Windows x64 and then set it up on VS project include and lib dependency paths from miniconda \Library directory(it contains lib, include).

But I have currently problems compiling GG because there are currently 62 errors(also VS 2022 project needs C++17 on GG)...

**Comment by o01eg** [comment]
Should be closed in #90

**Comment by geoffthemedio** [comment]
@o01eg FYI: I removed the x64 SDK files from the SDK releases since they are broken. Since it's fixed in master, the x64 v13 release can be kept, though.
